import type { Conta, PlanoContas } from "./types";

const c = (
  codigo: string,
  designacao: string,
  classe: string,
  natureza: Conta["natureza"],
  nivel: Conta["nivel"] = 1,
  usoFacultativo = false
): Conta => ({
  codigo,
  designacao,
  classe,
  natureza,
  nivel,
  usoFacultativo,
  fonte: "decreto-82-01"
});

export const SEED_CONTAS: Conta[] = [
  // CLASSE 0 — Contas de Ordem (facultativa)
  c("0", "Contas de Ordem", "0", "mista", 1, true),

  // CLASSE 1 — Meios Fixos e Investimentos
  c("1", "Meios Fixos e Investimentos", "1", "devedora", 1),
  c("11", "Imobilizações Corpóreas", "1", "devedora", 1),
  c("11.1", "Terrenos e Recursos Naturais", "1", "devedora", 2),
  c("11.1.1", "Terrenos em Bruto", "1", "devedora", 3),
  c("11.1.2", "Terrenos com Arranjos", "1", "devedora", 3),
  c("11.1.3", "Subsolos", "1", "devedora", 3),
  c("11.1.4", "Terrenos com Edifícios", "1", "devedora", 3),
  c("11.1.4.1", "Relativos a Edifícios Industriais", "1", "devedora", 4),
  c("11.1.4.2", "Relativos a Edifícios Administrativos e Comerciais", "1", "devedora", 4),
  c("11.1.4.3", "Relativos a Outros Edifícios", "1", "devedora", 4),
  c("11.2", "Edifícios e Outras Construções", "1", "devedora", 2),
  c("11.2.1", "Edifícios", "1", "devedora", 3),
  c("11.2.1.1", "Integrados em Conjuntos Industriais", "1", "devedora", 4),
  c("11.2.1.2", "Integrados em Conjuntos Administrativos e Comerciais", "1", "devedora", 4),
  c("11.2.1.3", "Outros Conjuntos Industriais", "1", "devedora", 4),
  c("11.2.1.4", "Implantados em Propriedade Alheia", "1", "devedora", 4),
  c("11.2.2", "Outras Construções", "1", "devedora", 3),
  c("11.2.3", "Instalações", "1", "devedora", 3),
  c("11.3", "Equipamento Básico", "1", "devedora", 2),
  c("11.3.1", "Material Industrial", "1", "devedora", 3),
  c("11.3.2", "Ferramentas Industriais", "1", "devedora", 3),
  c("11.3.3", "Melhoramentos em Equipamentos Básicos", "1", "devedora", 3),
  c("11.4", "Equipamento de Carga e Transporte", "1", "devedora", 2),
  c("11.5", "Equipamento Administrativo", "1", "devedora", 2),
  c("11.6", "Taras e Vasilhame", "1", "devedora", 2),
  c("11.9", "Outras Imobilizações Corpóreas", "1", "devedora", 2),

  c("12", "Imobilizações Incorpóreas", "1", "devedora", 1),
  c("12.1", "Trespasses", "1", "devedora", 2),
  c("12.2", "Despesas de Investigação e Desenvolvimento", "1", "devedora", 2),
  c("12.3", "Propriedade Industrial e Outros Direitos e Contratos", "1", "devedora", 2),
  c("12.4", "Despesas de Constituição", "1", "devedora", 2),
  c("12.9", "Outras Imobilizações Incorpóreas", "1", "devedora", 2),

  c("13", "Investimentos Financeiros", "1", "devedora", 1),
  c("13.1", "Empresas Subsidiárias", "1", "devedora", 2),
  c("13.1.1", "Partes de Capital", "1", "devedora", 3),
  c("13.1.2", "Obrigações e Títulos de Participação", "1", "devedora", 3),
  c("13.1.3", "Empréstimos", "1", "devedora", 3),
  c("13.2", "Empresas Associadas", "1", "devedora", 2),
  c("13.2.1", "Partes de Capital", "1", "devedora", 3),
  c("13.2.2", "Obrigações e Títulos de Participação", "1", "devedora", 3),
  c("13.2.3", "Empréstimos", "1", "devedora", 3),
  c("13.3", "Outras Empresas", "1", "devedora", 2),
  c("13.3.1", "Partes de Capital", "1", "devedora", 3),
  c("13.3.2", "Obrigações e Títulos de Participação", "1", "devedora", 3),
  c("13.3.3", "Empréstimos", "1", "devedora", 3),
  c("13.4", "Investimentos em Imóveis", "1", "devedora", 2),
  c("13.5", "Fundos", "1", "devedora", 2),
  c("13.9", "Outros Investimentos Financeiros", "1", "devedora", 2),
  c("13.9.1", "Diamantes", "1", "devedora", 3),
  c("13.9.2", "Ouro", "1", "devedora", 3),
  c("13.9.3", "Depósitos Bancários", "1", "devedora", 3),

  c("14", "Imobilizações em Curso", "1", "devedora", 1),
  c("14.1", "Obra em Curso", "1", "devedora", 2),
  c("14.2", "Obra em Curso", "1", "devedora", 2),
  c("14.7", "Adiantamentos por Conta de Imobilizado Corpóreo", "1", "devedora", 2),
  c("14.8", "Adiantamentos por Conta de Imobilizado Incorpóreo", "1", "devedora", 2),
  c("14.9", "Adiantamentos por Conta de Investimentos Financeiros", "1", "devedora", 2),

  c("18", "Amortizações Acumuladas", "1", "credora", 1),
  c("18.1", "Imobilizações Corpóreas", "1", "credora", 2),
  c("18.1.1", "Terrenos e Recursos Naturais", "1", "credora", 3),
  c("18.1.2", "Edifícios e Outras Construções", "1", "credora", 3),
  c("18.1.3", "Equipamento Básico", "1", "credora", 3),
  c("18.1.4", "Equipamento de Carga e Transporte", "1", "credora", 3),
  c("18.1.5", "Equipamento Administrativo", "1", "credora", 3),
  c("18.1.6", "Taras e Vasilhame", "1", "credora", 3),
  c("18.1.9", "Outras Imobilizações Corpóreas", "1", "credora", 3),
  c("18.2", "Imobilizações Incorpóreas", "1", "credora", 2),
  c("18.2.1", "Trespasses", "1", "credora", 3),
  c("18.2.2", "Despesas de Investigação e Desenvolvimento", "1", "credora", 3),
  c("18.2.3", "Propriedade Industrial e Outros Direitos e Contratos", "1", "credora", 3),
  c("18.2.4", "Despesas de Constituição", "1", "credora", 3),
  c("18.2.9", "Outras Imobilizações Incorpóreas", "1", "credora", 3),
  c("18.3", "Investimentos Financeiros em Imóveis", "1", "credora", 2),
  c("18.3.1", "Terrenos e Recursos Naturais", "1", "credora", 3),
  c("18.3.2", "Edifícios e Outras Construções", "1", "credora", 3),

  c("19", "Provisões para Investimentos Financeiros", "1", "credora", 1),
  c("19.1", "Empresas Subsidiárias", "1", "credora", 2),
  c("19.2", "Empresas Associadas", "1", "credora", 2),
  c("19.3", "Outras Empresas", "1", "credora", 2),
  c("19.4", "Fundos", "1", "credora", 2),
  c("19.9", "Outros Investimentos Financeiros", "1", "credora", 2),

  // CLASSE 2 — Existências
  c("2", "Existências", "2", "devedora", 1),
  c("21", "Compras", "2", "devedora", 1),
  c("21.1", "Matérias-Primas, Subsidiárias e de Consumo", "2", "devedora", 2),
  c("21.2", "Mercadorias", "2", "devedora", 2),
  c("21.7", "Devoluções de Compras", "2", "devedora", 2),
  c("21.8", "Descontos e Abatimentos em Compras", "2", "devedora", 2),

  c("22", "Matérias-Primas, Subsidiárias e de Consumo", "2", "devedora", 1),
  c("22.1", "Matérias-Primas", "2", "devedora", 2),
  c("22.2", "Matérias Subsidiárias", "2", "devedora", 2),
  c("22.3", "Materiais Diversos", "2", "devedora", 2),
  c("22.4", "Embalagens de Consumo", "2", "devedora", 2),
  c("22.5", "Outros Materiais", "2", "devedora", 2),

  c("23", "Produtos e Trabalhos em Curso", "2", "devedora", 1),
  c("24", "Produtos Acabados e Intermédios", "2", "devedora", 1),
  c("24.1", "Produtos Acabados", "2", "devedora", 2),
  c("24.2", "Produtos Intermédios", "2", "devedora", 2),
  c("24.9", "Em Poder de Terceiros", "2", "devedora", 2),

  c("25", "Subprodutos, Desperdícios, Resíduos e Refugos", "2", "devedora", 1),
  c("25.1", "Subprodutos", "2", "devedora", 2),
  c("25.2", "Desperdícios e Resíduos e Refugos", "2", "devedora", 2),

  c("26", "Mercadorias", "2", "devedora", 1),
  c("26.9", "Em Poder de Terceiros", "2", "devedora", 2),

  c("27", "Matérias-Primas, Mercadorias e Outros Materiais em Trânsito", "2", "devedora", 1),
  c("27.1", "Matérias-Primas", "2", "devedora", 2),
  c("27.2", "Outros Materiais", "2", "devedora", 2),
  c("27.3", "Mercadorias", "2", "devedora", 2),

  c("28", "Adiantamentos por Conta de Compras", "2", "devedora", 1),
  c("28.1", "Matérias-Primas e Outros Materiais", "2", "devedora", 2),
  c("28.2", "Mercadorias", "2", "devedora", 2),

  c("29", "Provisão para Depreciação de Existências", "2", "credora", 1),
  c("29.2", "Matérias-Primas, Subsidiárias e de Consumo", "2", "credora", 2),
  c("29.3", "Produtos e Trabalhos em Curso", "2", "credora", 2),
  c("29.4", "Produtos Acabados e Intermédios", "2", "credora", 2),
  c("29.5", "Subprodutos, Desperdícios, Resíduos e Refugos", "2", "credora", 2),
  c("29.6", "Mercadorias", "2", "credora", 2),

  // CLASSE 3 — Terceiros
  c("3", "Terceiros", "3", "mista", 1),
  c("31", "Clientes", "3", "devedora", 1),
  c("31.1", "Clientes — Correntes", "3", "devedora", 2),
  c("31.1.1", "Grupo", "3", "devedora", 3),
  c("31.1.1.1", "Subsidiárias", "3", "devedora", 4),
  c("31.1.1.2", "Associadas", "3", "devedora", 4),
  c("31.1.2", "Não Grupo", "3", "devedora", 3),
  c("31.1.2.1", "Nacionais", "3", "devedora", 4),
  c("31.1.2.2", "Estrangeiros", "3", "devedora", 4),
  c("31.2", "Clientes — Títulos a Receber", "3", "devedora", 2),
  c("31.3", "Clientes — Títulos Descontados", "3", "devedora", 2),
  c("31.8", "Clientes de Cobrança Duvidosa", "3", "devedora", 2),
  c("31.9", "Clientes — Saldos Credores", "3", "credora", 2),

  c("32", "Fornecedores", "3", "credora", 1),
  c("32.1", "Fornecedores — Correntes", "3", "credora", 2),
  c("32.1.1", "Grupo", "3", "credora", 3),
  c("32.1.2", "Não Grupo", "3", "credora", 3),
  c("32.2", "Fornecedores — Títulos a Pagar", "3", "credora", 2),
  c("32.8", "Fornecedores — Facturas em Recepção e Conferência", "3", "credora", 2),
  c("32.9", "Fornecedores — Saldos Devedores", "3", "devedora", 2),

  c("33", "Empréstimos", "3", "credora", 1),
  c("33.1", "Empréstimos Bancários", "3", "credora", 2),
  c("33.1.1", "Moeda Nacional", "3", "credora", 3),
  c("33.1.2", "Moeda Estrangeira", "3", "credora", 3),
  c("33.2", "Empréstimos por Obrigações", "3", "credora", 2),
  c("33.3", "Empréstimos por Títulos de Participação", "3", "credora", 2),
  c("33.9", "Outros Empréstimos Obtidos", "3", "credora", 2),

  c("34", "Estado", "3", "mista", 1),
  c("34.1", "Imposto sobre os Lucros", "3", "mista", 2),
  c("34.2", "Imposto de Produção e Consumo", "3", "mista", 2),
  c("34.3", "Imposto de Rendimento de Trabalho", "3", "mista", 2),
  c("34.4", "Imposto de Circulação", "3", "mista", 2),
  c("34.5", "IVA", "3", "mista", 2),
  c("34.5.1", "IVA Suportado", "3", "devedora", 3),
  c("34.5.1.1", "Existências", "3", "devedora", 4),
  c("34.5.1.2", "Meios Fixos e Investimentos", "3", "devedora", 4),
  c("34.5.1.3", "Outros Bens e Serviços", "3", "devedora", 4),
  c("34.5.2", "IVA Dedutível", "3", "devedora", 3),
  c("34.5.2.1", "Existências", "3", "devedora", 4),
  c("34.5.2.2", "Meios Fixos e Investimentos", "3", "devedora", 4),
  c("34.5.2.3", "Outros Bens e Serviços", "3", "devedora", 4),
  c("34.5.3", "IVA Liquidado", "3", "credora", 3),
  c("34.5.3.1", "Operações Gerais", "3", "credora", 4),
  c("34.5.3.2", "Operações Abrangidas pelo Regime de IVA de Caixa", "3", "credora", 4),
  c("34.5.3.3", "Autoconsumo e Operações Gratuitas", "3", "credora", 4),
  c("34.5.3.4", "Operações Especiais", "3", "credora", 4),
  c("34.5.4", "IVA Regularizações", "3", "mista", 3),
  c("34.5.5", "IVA Apuramento", "3", "mista", 3),
  c("34.5.6", "IVA a Pagar", "3", "credora", 3),
  c("34.5.7", "IVA a Recuperar", "3", "devedora", 3),
  c("34.5.8", "IVA Reembolsos Pedidos", "3", "devedora", 3),
  c("34.5.9", "IVA Liquidações Oficiosas", "3", "mista", 3),
  c("34.6", "Certificado de Crédito Fiscal a Compensar", "3", "devedora", 2),
  c("34.8", "Subsídios a Preços", "3", "devedora", 2),
  c("34.9", "Outros Impostos", "3", "mista", 2),

  c("35", "Entidades Participantes e Participadas", "3", "mista", 1),
  c("35.1", "Entidades Participantes", "3", "mista", 2),
  c("35.2", "Entidades Participadas", "3", "mista", 2),

  c("36", "Pessoal", "3", "mista", 1),
  c("36.1", "Pessoal — Remunerações", "3", "credora", 2),
  c("36.1.1", "Órgãos Sociais", "3", "credora", 3),
  c("36.1.2", "Empregados", "3", "credora", 3),
  c("36.2", "Pessoal — Participação nos Resultados", "3", "credora", 2),
  c("36.3", "Pessoal — Adiantamentos", "3", "devedora", 2),
  c("36.9", "Pessoal — Outros", "3", "mista", 2),

  c("37", "Outros Valores a Receber e a Pagar", "3", "mista", 1),
  c("37.1", "Compras de Imobilizado", "3", "credora", 2),
  c("37.1.1", "Corpóreo", "3", "credora", 3),
  c("37.1.2", "Incorpóreo", "3", "credora", 3),
  c("37.1.3", "Financeiro", "3", "credora", 3),
  c("37.2", "Vendas de Imobilizado", "3", "devedora", 2),
  c("37.3", "Proveitos a Facturar", "3", "devedora", 2),
  c("37.4", "Encargos a Repartir por Períodos Futuros", "3", "devedora", 2),
  c("37.5", "Encargos a Pagar", "3", "credora", 2),
  c("37.6", "Proveitos a Repartir por Períodos Futuros", "3", "credora", 2),
  c("37.7", "Contas Transitórias", "3", "mista", 2),
  c("37.9", "Outros Valores a Receber e a Pagar", "3", "mista", 2),

  c("38", "Provisões para Cobranças Duvidosas", "3", "credora", 1),
  c("38.1", "Provisões para Clientes", "3", "credora", 2),
  c("38.2", "Provisões para Saldos Devedores de Fornecedores", "3", "credora", 2),
  c("38.3", "Provisões p/Participantes e Participadas", "3", "credora", 2),
  c("38.4", "Provisões p/Dívidas do Pessoal", "3", "credora", 2),
  c("38.9", "Provisões para Outros Saldos a Receber", "3", "credora", 2),

  c("39", "Provisões para Outros Riscos e Encargos", "3", "credora", 1),
  c("39.1", "Provisões para Pensões", "3", "credora", 2),
  c("39.2", "Provisões para Processos Judiciais em Curso", "3", "credora", 2),
  c("39.3", "Provisões para Acidentes de Trabalho", "3", "credora", 2),
  c("39.4", "Provisões para Garantias Dadas a Clientes", "3", "credora", 2),
  c("39.9", "Provisões para Outros Riscos e Encargos", "3", "credora", 2),

  // CLASSE 4 — Meios Monetários
  c("4", "Meios Monetários", "4", "devedora", 1),
  c("41", "Títulos Negociáveis", "4", "devedora", 1),
  c("41.1", "Acções", "4", "devedora", 2),
  c("41.2", "Obrigações", "4", "devedora", 2),
  c("41.3", "Títulos da Dívida Pública", "4", "devedora", 2),

  c("42", "Depósitos a Prazo", "4", "devedora", 1),
  c("42.1", "Moeda Nacional", "4", "devedora", 2),
  c("42.2", "Moeda Estrangeira", "4", "devedora", 2),

  c("43", "Depósitos à Ordem", "4", "devedora", 1),
  c("43.1", "Moeda Nacional", "4", "devedora", 2),
  c("43.2", "Moeda Estrangeira", "4", "devedora", 2),

  c("44", "Outros Depósitos", "4", "devedora", 1),
  c("44.1", "Moeda Nacional", "4", "devedora", 2),
  c("44.2", "Moeda Estrangeira", "4", "devedora", 2),

  c("45", "Caixa", "4", "devedora", 1),
  c("45.1", "Fundo Fixo", "4", "devedora", 2),
  c("45.1.1", "Caixa Geral", "4", "devedora", 3),
  c("45.1.2", "Caixa Pequenas Despesas", "4", "devedora", 3),
  c("45.2", "Valores para Depositar", "4", "devedora", 2),
  c("45.3", "Valores Destinados a Pagamentos Específicos", "4", "devedora", 2),
  c("45.3.1", "Salários", "4", "devedora", 3),

  c("48", "Conta Transitória", "4", "mista", 1),
  c("48.1", "Banco A", "4", "mista", 2),
  c("48.2", "Banco B", "4", "mista", 2),

  c("49", "Provisões para Aplicações de Tesouraria", "4", "credora", 1),
  c("49.1", "Títulos Negociáveis", "4", "credora", 2),
  c("49.2", "Outras Aplicações de Tesouraria", "4", "credora", 2),

  // CLASSE 5 — Capital e Reservas
  c("5", "Capital e Reservas", "5", "credora", 1),
  c("51", "Capital", "5", "credora", 1),
  c("52", "Acções/Quotas Próprias", "5", "devedora", 1),
  c("52.1", "Valor Nominal", "5", "devedora", 2),
  c("52.2", "Descontos", "5", "devedora", 2),
  c("52.3", "Prémios", "5", "devedora", 2),

  c("53", "Prémios de Emissão", "5", "credora", 1),
  c("54", "Prestações Suplementares", "5", "credora", 1),
  c("55", "Reservas Legais", "5", "credora", 1),
  c("56", "Reservas de Reavaliação", "5", "credora", 1),
  c("56.1", "Legais", "5", "credora", 2),
  c("56.2", "Autónomas", "5", "credora", 2),

  c("57", "Reservas com Fins Especiais", "5", "credora", 1),
  c("58", "Reservas Livres", "5", "credora", 1),

  // CLASSE 6 — Proveitos e Ganhos por Natureza
  c("6", "Proveitos e Ganhos por Natureza", "6", "credora", 1),
  c("61", "Vendas", "6", "credora", 1),
  c("61.1", "Produtos Acabados e Intermédios", "6", "credora", 2),
  c("61.2", "Subprodutos, Desperdícios, Resíduos e Refugos", "6", "credora", 2),
  c("61.3", "Mercadorias", "6", "credora", 2),
  c("61.4", "Embalagens de Consumo", "6", "credora", 2),
  c("61.5", "Subsídios a Preços", "6", "credora", 2),
  c("61.7", "Devoluções", "6", "credora", 2),
  c("61.8", "Descontos e Abatimentos", "6", "credora", 2),

  c("62", "Prestações de Serviços", "6", "credora", 1),
  c("62.1", "Serviços Principais", "6", "credora", 2),
  c("62.2", "Serviços Secundários", "6", "credora", 2),
  c("62.8", "Descontos e Abatimentos", "6", "credora", 2),

  c("63", "Outros Proveitos Operacionais", "6", "credora", 1),
  c("63.1", "Serviços Suplementares", "6", "credora", 2),
  c("63.2", "Royalties", "6", "credora", 2),
  c("63.3", "Subsídios à Exploração", "6", "credora", 2),
  c("63.4", "Subsídios a Investimento", "6", "credora", 2),
  c("63.5", "IVA", "6", "credora", 2),
  c("63.8", "Outros Proveitos e Ganhos Operacionais", "6", "credora", 2),

  c("64", "Variação nos Inventários de Produtos Acabados e de Produção em Curso", "6", "mista", 1),
  c("65", "Trabalhos para a Própria Empresa", "6", "credora", 1),
  c("66", "Proveitos e Ganhos Financeiros Gerais", "6", "credora", 1),
  c("66.1", "Juros", "6", "credora", 2),
  c("66.2", "Diferenças de Câmbio Favoráveis", "6", "credora", 2),
  c("66.3", "Descontos de Pronto Pagamento Obtidos", "6", "credora", 2),
  c("66.4", "Rendimentos de Investimentos em Imóveis", "6", "credora", 2),
  c("66.5", "Rendimento de Participações de Capital", "6", "credora", 2),
  c("66.6", "Ganhos na Alienação de Aplicações Financeiras", "6", "credora", 2),
  c("66.7", "Redução de Provisões", "6", "credora", 2),

  c("67", "Proveitos e Ganhos Financeiros em Filiais e Associadas", "6", "credora", 1),
  c("68", "Outros Proveitos e Ganhos Não Operacionais", "6", "credora", 1),
  c("69", "Proveitos e Ganhos Extraordinários", "6", "credora", 1),

  // CLASSE 7 — Custos e Perdas por Natureza
  c("7", "Custos e Perdas por Natureza", "7", "devedora", 1),
  c("71", "Custo das Mercadorias Vendidas e das Matérias Consumidas", "7", "devedora", 1),
  c("71.1", "Matérias-Primas", "7", "devedora", 2),
  c("71.2", "Matérias Subsidiárias", "7", "devedora", 2),
  c("71.3", "Materiais Diversos", "7", "devedora", 2),
  c("71.4", "Embalagens de Consumo", "7", "devedora", 2),
  c("71.5", "Outros Materiais", "7", "devedora", 2),

  c("72", "Custos com o Pessoal", "7", "devedora", 1),
  c("72.1", "Remunerações — Órgãos Sociais", "7", "devedora", 2),
  c("72.2", "Remunerações — Pessoal", "7", "devedora", 2),
  c("72.3", "Pensões", "7", "devedora", 2),
  c("72.4", "Prémios para Pensões", "7", "devedora", 2),

  c("73", "Amortizações do Exercício", "7", "devedora", 1),
  c("73.1", "Imobilizações Corpóreas", "7", "devedora", 2),
  c("73.2", "Imobilizações Incorpóreas", "7", "devedora", 2),

  c("75", "Outros Custos e Perdas Operacionais", "7", "devedora", 1),
  c("75.1", "Subcontratos", "7", "devedora", 2),
  c("75.2", "Fornecimentos e Serviços de Terceiros", "7", "devedora", 2),
  c("75.2.11", "Água", "7", "devedora", 3),
  c("75.2.12", "Electricidade", "7", "devedora", 3),
  c("75.2.13", "Combustíveis e Outros Fluidos", "7", "devedora", 3),
  c("75.2.14", "Conservação e Reparação", "7", "devedora", 3),
  c("75.2.15", "Material de Protecção, Segurança e Conforto", "7", "devedora", 3),
  c("75.2.16", "Ferramentas e Utensílios de Desgaste Rápido", "7", "devedora", 3),
  c("75.2.17", "Material de Escritório", "7", "devedora", 3),
  c("75.2.18", "Livros e Documentação Técnica", "7", "devedora", 3),
  c("75.2.20", "Comunicação", "7", "devedora", 3),
  c("75.2.21", "Rendas e Alugueres", "7", "devedora", 3),
  c("75.2.22", "Seguros", "7", "devedora", 3),
  c("75.2.23", "Deslocações e Estadas", "7", "devedora", 3),
  c("75.2.24", "Despesas de Representação", "7", "devedora", 3),
  c("75.2.27", "Vigilância e Segurança", "7", "devedora", 3),
  c("75.2.28", "Limpeza, Higiene e Conforto", "7", "devedora", 3),
  c("75.2.29", "Publicidade e Propaganda", "7", "devedora", 3),
  c("75.2.30", "Contencioso e Notariado", "7", "devedora", 3),
  c("75.2.31", "Comissões a Intermediários", "7", "devedora", 3),
  c("75.2.32", "Assistência Técnica", "7", "devedora", 3),
  c("75.2.34", "Honorários e Avenças", "7", "devedora", 3),
  c("75.3", "Impostos", "7", "devedora", 2),
  c("75.3.1", "Indirectos", "7", "devedora", 3),
  c("75.3.1.1", "Imposto de Selo", "7", "devedora", 4),
  c("75.3.1.2", "IVA", "7", "devedora", 4),
  c("75.3.2", "Directos", "7", "devedora", 3),
  c("75.4", "Despesas Confidenciais", "7", "devedora", 2),
  c("75.5", "Quotizações", "7", "devedora", 2),
  c("75.6", "Ofertas e Amostras de Existências", "7", "devedora", 2),
  c("75.8", "Outros Custos e Perdas Operacionais", "7", "devedora", 2),

  c("76", "Custos e Perdas Financeiros Gerais", "7", "devedora", 1),
  c("76.1", "Juros", "7", "devedora", 2),
  c("76.2", "Diferenças de Câmbio Desfavoráveis", "7", "devedora", 2),
  c("76.3", "Descontos de Pronto Pagamento Concedidos", "7", "devedora", 2),
  c("76.4", "Amortizações de Investimentos em Imóveis", "7", "devedora", 2),
  c("76.5", "Provisões para Aplicações Financeiras", "7", "devedora", 2),
  c("76.6", "Perdas na Alienação de Aplicações Financeiras", "7", "devedora", 2),
  c("76.7", "Serviços Bancários", "7", "devedora", 2),

  c("77", "Custos e Perdas Financeiros em Filiais e Associadas", "7", "devedora", 1),

  c("78", "Outros Custos e Perdas Não Operacionais", "7", "devedora", 1),
  c("78.1", "Provisões do Exercício", "7", "devedora", 2),
  c("78.2", "Amortizações Extraordinárias", "7", "devedora", 2),
  c("78.3", "Perdas em Imobilizações", "7", "devedora", 2),
  c("78.4", "Perdas em Existências", "7", "devedora", 2),
  c("78.5", "Dívidas Incobráveis", "7", "devedora", 2),
  c("78.6", "Multas e Penalidades Contratuais", "7", "devedora", 2),
  c("78.6.1", "Fiscais", "7", "devedora", 3),
  c("78.6.2", "Não Fiscais", "7", "devedora", 3),
  c("78.6.3", "Penalidades Contratuais", "7", "devedora", 3),
  c("78.7", "Custos de Reestruturação", "7", "devedora", 2),
  c("78.8", "Descontinuidade de Operações", "7", "devedora", 2),
  c("78.9", "Alterações de Políticas Contabilísticas", "7", "devedora", 2),
  c("78.10", "Correcções Relativas a Exercícios Anteriores", "7", "devedora", 2),

  c("79", "Custos e Perdas Extraordinários", "7", "devedora", 1),

  // CLASSE 8 — Resultados
  c("8", "Resultados", "8", "credora", 1),
  c("81", "Resultados Transitados", "8", "mista", 1),
  c("81.1", "Ano Exercício Anterior", "8", "mista", 2),
  c("81.1.1", "Resultado do Ano", "8", "mista", 3),
  c("81.1.2", "Aplicação de Resultados", "8", "mista", 3),
  c("81.2", "Anos Anteriores", "8", "mista", 2),
  c("81.2.1", "Resultado do Ano", "8", "mista", 3),
  c("81.2.2", "Aplicação de Resultados", "8", "mista", 3),

  c("82", "Resultados Operacionais", "8", "mista", 1),
  c("82.1", "Vendas", "8", "credora", 2),
  c("82.2", "Prestações de Serviços", "8", "credora", 2),
  c("82.3", "Outros Proveitos Operacionais", "8", "credora", 2),
  c("82.4", "Variação nos Inventários", "8", "mista", 2),
  c("82.5", "Trabalhos para a Própria Empresa", "8", "credora", 2),
  c("82.6", "Custo das Mercadorias Vendidas e das Matérias Consumidas", "8", "devedora", 2),
  c("82.7", "Custos com o Pessoal", "8", "devedora", 2),
  c("82.8", "Amortizações do Exercício", "8", "devedora", 2),
  c("82.9", "Outros Custos Operacionais", "8", "devedora", 2),

  c("83", "Resultados Financeiros", "8", "mista", 1),
  c("84", "Resultados Financeiros em Filiais e Associadas", "8", "mista", 1),
  c("85", "Resultados Não Operacionais", "8", "mista", 1),
  c("86", "Resultados Extraordinários", "8", "mista", 1),
  c("87", "Impostos sobre os Lucros", "8", "devedora", 1),
  c("88", "Resultado Líquido do Exercício", "8", "mista", 1),
  c("88.1", "Resultados Operacionais", "8", "mista", 2),
  c("88.2", "Resultados Financeiros Gerais", "8", "mista", 2),
  c("88.3", "Resultados em Filiais e Associadas", "8", "mista", 2),
  c("88.4", "Resultados Não Operacionais", "8", "mista", 2),
  c("88.5", "Imposto sobre os Resultados Correntes", "8", "devedora", 2),
  c("88.6", "Resultados Extraordinários", "8", "mista", 2),
  c("88.7", "Imposto sobre os Resultados Extraordinários", "8", "devedora", 2),
  c("88.9", "Transferência para Resultados Transitados", "8", "mista", 2),

  c("89", "Dividendos Antecipados", "8", "devedora", 1),

  // CLASSE 9 — Contabilidade Analítica (facultativa)
  c("9", "Contabilidade Analítica", "9", "mista", 1, true),
];

export function construirPlano(contas: Conta[] = SEED_CONTAS): PlanoContas {
  return {
    norma: "PGC_ANGOLA_82_2001",
    diploma: "Decreto n.º 82/01, de 16 de Novembro",
    versao: "decreto-82-01-v1",
    contas,
  };
}
